# Generated by Django 6.0 on 2025-12-24 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='hostel',
        ),
    ]
