# Generated by Django 6.0 on 2026-01-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesapp', '0009_complaint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='message',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='subject',
            new_name='title',
        ),
        migrations.AddField(
            model_name='complaint',
            name='admin_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
