# Generated by Django 6.0 on 2026-01-07 16:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesapp', '0010_rename_message_complaint_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='subject',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
