# Generated by Django 6.0 on 2026-01-07 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesapp', '0011_complaint_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='description',
            new_name='message',
        ),
    ]
