# Generated by Django 6.0 on 2026-01-07 17:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesapp', '0013_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='month',
        ),
        migrations.AddField(
            model_name='bill',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
