# Generated by Django 6.0 on 2026-01-08 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesapp', '0016_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='title',
        ),
    ]
