# Generated by Django 6.0 on 2026-01-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesapp', '0017_remove_complaint_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Pending Approval', 'Pending Approval'), ('Paid', 'Paid')], default='Unpaid', max_length=20),
        ),
    ]
