# Generated by Django 6.0 on 2026-01-11 16:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesapp', '0018_bill_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together={('student', 'start_date', 'end_date')},
        ),
    ]
